id: IDA4F44D3
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-26T15:41:29+00:00'
last_modified: '2022-06-07T15:06:57.523679+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W1AC218
  title: ཀུན་མཁྱེན་འཇམ་དབྱངས་བཞད་པའི་འདུལ་བའི་སྤྱི་དོན། ༼སྟོན་ཆ༽ ༼སྨད་ཆ༽
  author: ''
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
  base:
    7E6A:
      image_group_id: I2PD18580
      title: ''
      total_pages: 538
      order: 1
      base_file: 7E6A.txt
    CF0A:
      image_group_id: I2PD18581
      title: ''
      total_pages: 342
      order: 2
      base_file: CF0A.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
