id: P001777
initial_creation_type: ocr
created_at: 26/03/2020
last_modified_at: 2021-12-17 10:21:02.926161
source_metadata:
  id: bdr:W1AC218
  title: ཀུན་མཁྱེན་འཇམ་དབྱངས་བཞད་པའི་འདུལ་བའི་སྤྱི་དོན། ༼སྟོན་ཆ༽ ༼སྨད་ཆ༽
  author: ''
  volumes:
    3d8549a78e64473898b6259a374b33e3:
      image_group_id: I2PD18580
      title: ''
      volume_number: 1
      total_pages: 538
      base_file: v001.txt
    9922afd43e894d4eb8aba5b96c1e58b3:
      image_group_id: I2PD18581
      title: ''
      volume_number: 2
      total_pages: 342
      base_file: v002.txt
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
