id: P001777
initial_creation_type: ocr
source_metadata:
  id: bdr:W1AC218
  title: ཀུན་མཁྱེན་འཇམ་དབྱངས་བཞད་པའི་འདུལ་བའི་སྤྱི་དོན། ༼སྟོན་ཆ༽ ༼སྨད་ཆ༽
  author: ''
  volumes:
    3d8549a78e64473898b6259a374b33e3:
      image_group_id: I2PD18580
      title: ''
      volume_number: 1
      total_pages: 538
    9922afd43e894d4eb8aba5b96c1e58b3:
      image_group_id: I2PD18581
      title: ''
      volume_number: 2
      total_pages: 342
